# Root logger level set to ERROR
log4j.rootLogger=ERROR, stdout

# Appender to console
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{HH:mm:ss} %-5p %c - %m%n

# Suppress TestNG internal log messages
log4j.logger.org.testng.internal.Utils=OFF
